[package]
name = "diatermi"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["alejandro"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
opt-level = 0
[profile.release]
opt-level = 3
[dependencies]
crossterm = "0.27.0"
